# Site settings
title: #add title
email: #add email
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://andrew-max.com" # the base hostname & protocol for your site
github_username: #git hub user name
cdn_url: #the url of the bucket or cdn which holds your photos
# Build settings
markdown: kramdown
permalink: pretty
main_img_url: #url to the photo which shows up in the header
